CATEGORIES = [
    "Housing",
    "Groceries",
    "Dining Out",
    "Food",
    "Transport",
    "Healthcare",
    "Wellness",
    "Entertainment",
    "Shopping",
    "Travel",
    "Utilities",
    "Subscriptions",
    "Other",
]
