// Pulls the Material Symbols the app uses out of Google's official package
// and writes them into src/components/materialSymbols.ts, so the app ships
// only these paths instead of depending on the full set of ~7,800 icons.
//
//   node scripts/material-symbols.mjs
//
// To add an icon: put its Material Symbols name in NAMES (browse
// https://fonts.google.com/icons, style Rounded), run this, and use it with
// <Symbol name="..."/> or a named wrapper in Icons.tsx. "-fill" adds the
// filled variant, used for the active item in navigation.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const PACKAGE = "@material-symbols/svg-400";
const VERSION = "0.47.5";
const STYLE = "rounded";

const NAMES = [
  // Actions and controls.
  "arrow_back", "settings", "edit", "delete", "close", "check", "receipt_long",
  "upload_file", "photo_camera", "image", "menu", "chevron_right", "logout",
  "refresh", "schedule", "wifi_off", "warning", "visibility", "visibility_off",
  "remove", "add", "keyboard_arrow_down", "trending_up", "trending_down", "group_add",
  "add_circle", "payments", "mail", "account_balance_wallet-fill",
  "light_mode", "dark_mode", "brightness_auto",
  "unfold_more", "arrow_upward", "arrow_downward", "search", "label", "download", "calendar_month",
  "filter_list",
  // Navigation, outlined and filled (filled marks the current page).
  "home", "home-fill", "add_circle-fill", "list_alt", "list_alt-fill",
  "bar_chart", "bar_chart-fill", "handshake", "handshake-fill",
  "notifications", "notifications-fill", "group", "group-fill",
  "account_circle", "account_circle-fill", "credit_card", "credit_card-fill",
];

const dir = mkdtempSync(join(tmpdir(), "material-symbols-"));
try {
  const tgz = execFileSync("npm", ["pack", `${PACKAGE}@${VERSION}`, "--silent"], { cwd: dir }).toString().trim().split("\n").pop();
  const files = NAMES.map((n) => `package/${STYLE}/${n}.svg`);
  execFileSync("tar", ["xzf", tgz, ...files], { cwd: dir });
  const entries = NAMES.map((n) => {
    const svg = readFileSync(join(dir, "package", STYLE, `${n}.svg`), "utf8");
    const d = svg.match(/<path d="([^"]+)"/)?.[1];
    if (!d || (svg.match(/<path /g) ?? []).length !== 1) throw new Error(`${n}: expected one path`);
    return `  ${JSON.stringify(n)}: ${JSON.stringify(d)},`;
  });
  const out = `// Generated by scripts/material-symbols.mjs. Do not edit by hand.
//
// Material Symbols, ${STYLE}, weight 400, from ${PACKAGE}@${VERSION}.
// Copyright Google LLC. Licensed under the Apache License, Version 2.0:
// https://www.apache.org/licenses/LICENSE-2.0
//
// Each value is the single path of the icon, drawn in viewBox "0 -960 960 960".

export const SYMBOLS = {
${entries.join("\n")}
} as const;

export type SymbolName = keyof typeof SYMBOLS;
`;
  writeFileSync(new URL("../src/components/materialSymbols.ts", import.meta.url), out);
  console.log(`wrote ${NAMES.length} symbols`);
} finally {
  rmSync(dir, { recursive: true, force: true });
}
